version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  signalr1:
    build:
      context: ./SignalRServer
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION=redis:6379
    depends_on:
      - redis
    ports:
      - "5001:80"
  signalr2:
    build:
      context: ./SignalRServer
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION=redis:6379
    depends_on:
      - redis
    ports:
      - "5002:80"
  angular-client:
    build:
      context: ./signalr-client
    depends_on:
      - signalr1
      - signalr2
    ports:
      - "4200:80" 